### ISSUE TITLE
Upgrade to lodash@^3.0.0

### ISSUE THREAD

**Issue by Gafoor786** [Azure/azure-mobile-apps-js-client#62] opened 2016-01-06 05:27 UTC
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
C:\Users\787904\AppData\Roaming\npm\gulp -> C:\Users\787904\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js
C:\Users\787904\AppData\Roaming\npm
└─┬ gulp@3.9.0
  ├─┬ chalk@1.1.1
  │ └── escape-string-regexp@1.0.4
  ├─┬ gulp-util@3.0.7
  │ ├─┬ dateformat@1.0.12
  │ │ └─┬ meow@3.7.0
  │ │   ├── decamelize@1.1.2
  │ │   └─┬ normalize-package-data@2.3.5
  │ │     └─┬ is-builtin-module@1.0.0
  │ │       └── builtin-modules@1.1.1
  │ └─┬ through2@2.0.0
  │   └─┬ readable-stream@2.0.5
  │     └── process-nextick-args@1.0.6
  ├── v8flags@2.0.11
  └─┬ vinyl-fs@0.3.14
    └─┬ strip-bom@1.0.0
      └── is-utf8@0.2.1

**Comment by adrianhall** [comment] 2016-03-14 19:24
Dupe of #20

**Closed by adrianhall** 2016-03-14 19:24 UTC
Labels: Code Cleanup, Resolution-Duplicate
